### ISSUE TITLE
TypeError: 'str' does not support the buffer interface

### ISSUE THREAD

**Issue by aditiapratama** [bil-elmoussaoui/Hardcode-Tray#100]
I've updated to the recent version, and when I try to run it, I've got following error

```python
Traceback (most recent call last):
  File "script.py", line 461, in <module>
    if detect_de() in ("pantheon", "xfce"):
  File "script.py", line 60, in detect_de
    if " = \"xfce4\"" in out:
TypeError: 'str' does not support the buffer interface
```

**Comment by bil-elmoussaoui** [comment]
Which distro you're using ?

**Comment by aditiapratama** [comment]
I'm using xubuntu 15.04

**Comment by bil-elmoussaoui** [comment]
Add this after the line  59 
`print(out)` and paste the output here

**Comment by aditiapratama** [comment]
still got same error
```python
b''
Traceback (most recent call last):
  File "script.py", line 462, in <module>
    if detect_de() in ("pantheon", "xfce"):
  File "script.py", line 61, in detect_de
    if " = \"xfce4\"" in out:
TypeError: 'str' does not support the buffer interface
```

**Comment by wa4557** [comment]
Should be fixed now, @aditiapratama please try again

**Comment by aditiapratama** [comment]
Sorry, for delay, yes it's already fixed. Thank you
