### ISSUE TITLE
Bug on fedora

### ISSUE THREAD

**Issue by bil-elmoussaoui** [bil-elmoussaoui/Hardcode-Tray#121]
I had this issue today when i tried the script again on fedora 
```bash
Traceback (most recent call last):
  File "script.py", line 509, in <module>
    install()
  File "script.py", line 386, in install
    real_icons = get_correct_chrome_icons(apps[app], pak_file)
  File "script.py", line 190, in get_correct_chrome_icons
    execute([dirname + "data_pack.py", dirname + pak_file])
  File "script.py", line 119, in execute
    p = Popen(command_list, stdout=PIPE, stderr=PIPE)
  File "/usr/lib64/python3.4/subprocess.py", line 859, in __init__
    restore_signals, start_new_session)
  File "/usr/lib64/python3.4/subprocess.py", line 1457, in _execute_child
    raise child_exception_type(errno_num, err_msg)
PermissionError: [Errno 13] Permission non accordée
```

**Comment by bil-elmoussaoui** [comment]
This is not happening anymore.. closing
