### ISSUE TITLE
Issues 

### ISSUE THREAD

**Issue by leoheck** [bil-elmoussaoui/Hardcode-Tray#146]
```
fixing failed with error:
	Traceback (most recent call last):
	  File "./data_pack.py", line 136, in <module>
	    main()
	  File "./data_pack.py", line 129, in main
	    dataPack = ReadDataPack(filename)
	  File "./data_pack.py", line 46, in ReadDataPack
	    data = ReadFile(input_file, BINARY)
	  File "./data_pack.py", line 38, in ReadFile
	    with open(filename, mode) as f:
	FileNotFoundError: [Errno 2] No such file or directory: 'chrome_100_percent.pak'
	
fixing failed with error:
	Traceback (most recent call last):
	  File "./data_pack.py", line 136, in <module>
	    main()
	  File "./data_pack.py", line 129, in main
	    dataPack = ReadDataPack(filename)
	  File "./data_pack.py", line 46, in ReadDataPack
	    data = ReadFile(input_file, BINARY)
	  File "./data_pack.py", line 38, in ReadFile
	    with open(filename, mode) as f:
	FileNotFoundError: [Errno 2] No such file or directory: 'chrome_100_percent.pak'
	mv: cannot stat ‘chrome_100_percent.pak’: No such file or directory
	
fixing failed with error:
	Traceback (most recent call last):
	  File "./data_pack.py", line 136, in <module>
	    main()
	  File "./data_pack.py", line 129, in main
	    dataPack = ReadDataPack(filename)
	  File "./data_pack.py", line 46, in ReadDataPack
	    data = ReadFile(input_file, BINARY)
	  File "./data_pack.py", line 38, in ReadFile
	    with open(filename, mode) as f:
	FileNotFoundError: [Errno 2] No such file or directory: 'resources.pak'
	
fixing failed with error:
	Traceback (most recent call last):
	  File "./data_pack.py", line 136, in <module>
	    main()
	  File "./data_pack.py", line 129, in main
	    dataPack = ReadDataPack(filename)
	  File "./data_pack.py", line 46, in ReadDataPack
	    data = ReadFile(input_file, BINARY)
	  File "./data_pack.py", line 38, in ReadFile
	    with open(filename, mode) as f:
	FileNotFoundError: [Errno 2] No such file or directory: 'resources.pak'
	mv: cannot stat ‘resources.pak’: No such file or directory
	
fixing failed with error:
	cp: cannot stat ‘/opt/spotify/spotify-client/Data//resources.zip’: No such file or directory
	unzip:  cannot find or open resources_old.zip, resources_old.zip.zip or resources_old.zip.ZIP.
	
fixing failed with error:
	./database/scripts/spotify: line 18: cd: resources_old/: No such file or directory
```

**Comment by bil-elmoussaoui** [comment]
Hello, 
Thanks for trying Hardcode-Tray; the issues you've reported will be fixed once the fix of #141 will be released! 
I will keep you updated here once we release it.

**Comment by leoheck** [comment]
Thank you too. I haven't had time to say something but the errors seemed to be self-explanatory. :+1:

**Comment by Foggalong** [comment]
I'm having similar problems

```
Spotify -- fixed using spotify-indicator
fixing failed with error:
	Traceback (most recent call last):
	  File "./data_pack.py", line 136, in <module>
	    main()
	  File "./data_pack.py", line 129, in main
	    dataPack = ReadDataPack(filename)
	  File "./data_pack.py", line 46, in ReadDataPack
	    data = ReadFile(input_file, BINARY)
	  File "./data_pack.py", line 38, in ReadFile
	    with open(filename, mode) as f:
	FileNotFoundError: [Errno 2] No such file or directory: 'resources.pak'
	mv: cannot stat 'resources.pak': No such file or directory
	
fixing failed with error:
	cp: cannot stat '/opt/spotify/spotify-client/Data//resources.zip': No such file or directory
	unzip:  cannot find or open resources_old.zip, resources_old.zip.zip or resources_old.zip.ZIP.
	Traceback (most recent call last):
	  File "svgtopng.py", line 42, in <module>
	    convert_svg2png(infile, outfile)
	  File "svgtopng.py", line 31, in convert_svg2png
	    fout = open(outfile, "wb")
	FileNotFoundError: [Errno 2] No such file or directory: 'resources_old/_linux/spotify_icon.ico'
	
fixing failed with error:
	Traceback (most recent call last):
	  File "svgtopng.py", line 42, in <module>
	    convert_svg2png(infile, outfile)
	  File "svgtopng.py", line 31, in convert_svg2png
	    fout = open(outfile, "wb")
	FileNotFoundError: [Errno 2] No such file or directory: 'resources_old/_linux/spotify-linux-16.png'
	
fixing failed with error:
	Traceback (most recent call last):
	  File "svgtopng.py", line 42, in <module>
	    convert_svg2png(infile, outfile)
	  File "svgtopng.py", line 31, in convert_svg2png
	    fout = open(outfile, "wb")
	FileNotFoundError: [Errno 2] No such file or directory: 'resources_old/_linux/spotify-linux-22.png'
	
fixing failed with error:
	Traceback (most recent call last):
	  File "svgtopng.py", line 42, in <module>
	    convert_svg2png(infile, outfile)
	  File "svgtopng.py", line 31, in convert_svg2png
	    fout = open(outfile, "wb")
	FileNotFoundError: [Errno 2] No such file or directory: 'resources_old/_linux/spotify-linux-24.png'
	
fixing failed with error:
	Traceback (most recent call last):
	  File "svgtopng.py", line 42, in <module>
	    convert_svg2png(infile, outfile)
	  File "svgtopng.py", line 31, in convert_svg2png
	    fout = open(outfile, "wb")
	FileNotFoundError: [Errno 2] No such file or directory: 'resources_old/_linux/spotify-linux-32.png'
	
fixing failed with error:
	Traceback (most recent call last):
	  File "svgtopng.py", line 42, in <module>
	    convert_svg2png(infile, outfile)
	  File "svgtopng.py", line 31, in convert_svg2png
	    fout = open(outfile, "wb")
	FileNotFoundError: [Errno 2] No such file or directory: 'resources_old/_linux/spotify-linux-48.png'
	
fixing failed with error:
	Traceback (most recent call last):
	  File "svgtopng.py", line 42, in <module>
	    convert_svg2png(infile, outfile)
	  File "svgtopng.py", line 31, in convert_svg2png
	    fout = open(outfile, "wb")
	FileNotFoundError: [Errno 2] No such file or directory: 'resources_old/_linux/spotify-linux-64.png'
	
fixing failed with error:
	Traceback (most recent call last):
	  File "svgtopng.py", line 42, in <module>
	    convert_svg2png(infile, outfile)
	  File "svgtopng.py", line 31, in convert_svg2png
	    fout = open(outfile, "wb")
	FileNotFoundError: [Errno 2] No such file or directory: 'resources_old/_linux/spotify-linux-128.png'
	
fixing failed with error:
	Traceback (most recent call last):
	  File "svgtopng.py", line 42, in <module>
	    convert_svg2png(infile, outfile)
	  File "svgtopng.py", line 31, in convert_svg2png
	    fout = open(outfile, "wb")
	FileNotFoundError: [Errno 2] No such file or directory: 'resources_old/_linux/spotify-linux-256.png'
	
fixing failed with error:
	Traceback (most recent call last):
	  File "svgtopng.py", line 42, in <module>
	    convert_svg2png(infile, outfile)
	  File "svgtopng.py", line 31, in convert_svg2png
	    fout = open(outfile, "wb")
	FileNotFoundError: [Errno 2] No such file or directory: 'resources_old/_linux/spotify-linux-512.png'
	./database/scripts/spotify: line 18: cd: resources_old/: No such file or directory
	
```

**Comment by bil-elmoussaoui** [comment]
Sorry guys! I will try to fix those issues this weekend! Really busy with school:/

**Comment by bil-elmoussaoui** [comment]
Fixed thanks to @wa4557 :+1:
