### ISSUE TITLE
Script breaking.. 

### ISSUE THREAD

**Issue by leoheck** [bil-elmoussaoui/Hardcode-Tray#180]
The app breaks here:

```bash
/opt/Hardcode-Tray/database/scripts » sudo -E hardcode-tray                                                                                              lheck@moon
Welcome to the tray icons hardcoder fixer!
Your indicator icon size is : 22
Your current icon theme is : Numix-Circle
Svg to png functions are : Enabled
Applications will be fixed : All
1 - Apply
2 - Revert
Please choose: 1
Applying now..

Dropbox -- fixed using dropboxstatus-busy
Dropbox -- fixed using dropboxstatus-busy2
Dropbox -- fixed using dropboxstatus-idle
Dropbox -- fixed using dropboxstatus-logo
Dropbox -- fixed using dropboxstatus-x
Google Chrome (Beta) -- fixed using google-chrome-tray
Megasync -- fixed using megasync-status-paused
Megasync -- fixed using megasync-status-disconnected
Megasync -- fixed using megasync-status-syncing
Megasync -- fixed using megasync-status-ok
Skype -- fixed using skype-status-away
Skype -- fixed using skype-status-away-notification
Skype -- fixed using skype-status-connected
Skype -- fixed using skype-status-connected-notification
Skype -- fixed using skype-status-connecting-0
Skype -- fixed using skype-status-connecting-1
Skype -- fixed using skype-status-connecting-2
Skype -- fixed using skype-status-connecting-3
Skype -- fixed using skype-status-disturb
Skype -- fixed using skype-status-disturb-notification
Skype -- fixed using skype-status-invisible
Skype -- fixed using skype-status-invisible-notification
Skype -- fixed using skype-status-offline
Skype -- fixed using skype-status-offline-notification
Skype -- fixed using skype-indicator
Skype -- fixed using skype-status-hidden
Teamviewer 11 -- fixed using teamviewer-indicator
Teamviewer 11 -- fixed using teamviewer-indicator-error
Teamviewer 11 -- fixed using teamviewer-indicator-connected
Teamviewer 11 -- fixed using teamviewer-indicator-away
Teamviewer 11 -- fixed using teamviewer-indicator-offline
Teamviewer 11 -- fixed using teamviewer-indicator-busy
Whatsie -- fixed using whatsie-tray
Whatsie -- fixed using whatsie-tray-attention


fixing failed with error:
	Traceback (most recent call last):
	  File "/opt/Hardcode-Tray/database/scripts/electron", line 56, in <module>
	    fileinfo = getFromDict(files, keys)
	  File "/opt/Hardcode-Tray/database/scripts/electron", line 14, in getFromDict
	    return reduce(lambda d, k: d[k], mapList, dataDict)
	  File "/opt/Hardcode-Tray/database/scripts/electron", line 14, in <lambda>
	    return reduce(lambda d, k: d[k], mapList, dataDict)
	KeyError: 'tray-skypeTemplate@2x.png'

Done , Thank you for using the Hardcode-Tray fixer!
```

And the icons seems to be the same.

**Comment by Floofies** [comment]
Hi, what version are you using? Find out with: `hardcode-tray --version`
Also, what OS?

**Comment by leoheck** [comment]
Same as you, v3.1

**Comment by leoheck** [comment]
Is it possible that this script made my computer don't start anymore? After the unity loguin, the gui starts load (the status bar is initializing with clock and system butrons but no 3rt-party icons) then it suddenly logs me out.

**Comment by Floofies** [comment]
@leoheck Check permissions of `/home` and all folders within. See #172 & #176
I would upgrade from v3.1 to the latest git version right away as well.

**Comment by leoheck** [comment]
Oh, great @Floofies! Inside my home all files were ok, but I miss that verification. Why are you changing such permission? Thanks anyway.

**Comment by bil-elmoussaoui** [comment]
This issue was fixed on master branch! i will push a new version soon, see #171

**Comment by leoheck** [comment]
This is the master branch and the version says v3.1

**Comment by bil-elmoussaoui** [comment]
Once you've cloned the version you will need to execute `sudo -E python3 script.py ...` instead of `hardcode-tray ...`
