### ISSUE TITLE
cli switches not working

### ISSUE THREAD

**Issue by edgard** [bil-elmoussaoui/Hardcode-Tray#188]
Hi Bil, seems that the apply and revert switch are not working since the code refactor. Or is just with me? :D

**Comment by bil-elmoussaoui** [comment]
Do you have any error msg?

**Comment by edgard** [comment]
Nothing really, it just show the 1) apply or 2) revert options like I haven't passed any cli parameters.

**Comment by bil-elmoussaoui** [comment]
What are you runing? I mean the command you type on terminal + cli

**Comment by bil-elmoussaoui** [comment]
Fixed that upstream

**Comment by varlesh** [comment]
With fresh git version ( option -ug):
```
alex@dell:/tmp$ hardcode-tray
Traceback (most recent call last):
  File "/opt/Hardcode-Tray/script.py", line 75, in <module>
    "svgtopng", "%s/database/scripts/svgtopng.py" % absolute_path)
  File "/usr/lib/python3.5/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/opt/Hardcode-Tray//database/scripts/svgtopng.py", line 8, in <module>
    require_version('Rsvg', '2.0')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 102, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Rsvg not available
alex@dell:/tmp$ 

```

**Comment by bil-elmoussaoui** [comment]
@varlesh The issue shouldn't be shown any more, but you will need to have Rsvg installed in your system! it's a library i used to fix #184...

**Comment by varlesh** [comment]
OMG - when script working on my PC open hardcoded icons on Inkscape in fullscreenmode

**Comment by varlesh** [comment]
an error:
```
fixing failed with error:
        Traceback (most recent call last):
          File "/opt/Hardcode-Tray/database/scripts/chrome", line 19, in <module>
            pngbytes = svgtopng.convert_svg2bin(icon_for_repl)
          File "/opt/Hardcode-Tray/database/scripts/svgtopng.py", line 75, in convert_svg2bin
            with open('/tmp/hardcode.png', 'rb') as temppng:
        FileNotFoundError: [Errno 2] No such file or directory: '/tmp/hardcode.png'

fixing failed with error:
        Traceback (most recent call last):
          File "/opt/Hardcode-Tray/database/scripts/electron", line 73, in <module>
            pngbytes = svgtopng.convert_svg2bin(icon_for_repl)
          File "/opt/Hardcode-Tray/database/scripts/svgtopng.py", line 75, in convert_svg2bin
            with open('/tmp/hardcode.png', 'rb') as temppng:
        FileNotFoundError: [Errno 2] No such file or directory: '/tmp/hardcode.png'


Done , Thank you for using the Hardcode-Tray fixer!

```

**Comment by bil-elmoussaoui** [comment]
Because it does not detect RSVG so it uses inksape instead, please install Rsvg first ;) should be in your repository

**Comment by varlesh** [comment]
I'm use rsvg-convert for convert SVG to PNG. Working very good, package librsvg2-bin

**Comment by bil-elmoussaoui** [comment]
I know there's bunch of scripts that can do that, but i wanted to use Python code to not add more dependecies :P Can you go to /tmp and look if you will find an icon with `hardcode.png` name?

**Comment by varlesh** [comment]
/tmp/hardcode.png not available

**Comment by bil-elmoussaoui** [comment]
Should be fixed on latest git version

**Comment by varlesh** [comment]
i'm have inkscape (because nedd for draw and work for me) and rsvg... and script open icons on inkscape in fullscreen

**Comment by varlesh** [comment]
> Should be fixed on latest git version

Ok, test

**Comment by bil-elmoussaoui** [comment]
Fixed Inksape opening gui to convert svg to png files ;)

**Comment by varlesh** [comment]
inkscape not opening, but ave errors:
```
fixing failed with error:
        Traceback (most recent call last):
          File "/opt/Hardcode-Tray/database/scripts/qt-tray", line 15, in <module>
            svgtopng.convert_svg2png(origfile, symlfile)
          File "/opt/Hardcode-Tray/database/scripts/svgtopng.py", line 37, in convert_svg2png
            stdout=PIPE, stderr=PIPE)
          File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
            restore_signals, start_new_session)
          File "/usr/lib/python3.5/subprocess.py", line 1551, in _execute_child
            raise child_exception_type(errno_num, err_msg)
        FileNotFoundError: [Errno 2] No such file or directory: 'inkscape -z'

fixing failed with error:
        Traceback (most recent call last):
          File "/opt/Hardcode-Tray/database/scripts/chrome", line 19, in <module>
            pngbytes = svgtopng.convert_svg2bin(icon_for_repl)
          File "/opt/Hardcode-Tray/database/scripts/svgtopng.py", line 73, in convert_svg2bin
            stdout=PIPE, stderr=PIPE)
          File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
            restore_signals, start_new_session)
          File "/usr/lib/python3.5/subprocess.py", line 1551, in _execute_child
            raise child_exception_type(errno_num, err_msg)
        FileNotFoundError: [Errno 2] No such file or directory: 'inkscape -z'

fixing failed with error:
        Traceback (most recent call last):
          File "/opt/Hardcode-Tray/database/scripts/electron", line 73, in <module>
            pngbytes = svgtopng.convert_svg2bin(icon_for_repl)
          File "/opt/Hardcode-Tray/database/scripts/svgtopng.py", line 73, in convert_svg2bin
            stdout=PIPE, stderr=PIPE)
          File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
            restore_signals, start_new_session)
          File "/usr/lib/python3.5/subprocess.py", line 1551, in _execute_child
            raise child_exception_type(errno_num, err_msg)
        FileNotFoundError: [Errno 2] No such file or directory: 'inkscape -z'


Done , Thank you for using the Hardcode-Tray fixer!
```

**Comment by varlesh** [comment]
Maybe better replace inkscape to rsvg-convert. It's easy and fast util:
Options:
```
-d, --dpi-x=<float>                                         pixels per inch [optional; defaults to 90dpi]
  -p, --dpi-y=<float>                                         pixels per inch [optional; defaults to 90dpi]
  -x, --x-zoom=<float>                                        x zoom factor [optional; defaults to 1.0]
  -y, --y-zoom=<float>                                        y zoom factor [optional; defaults to 1.0]
  -z, --zoom=<float>                                          zoom factor [optional; defaults to 1.0]
  -w, --width=<int>                                           width [optional; defaults to the SVG's width]
  -h, --height=<int>                                          height [optional; defaults to the SVG's height]
  -f, --format=[png, pdf, ps, eps, svg, xml, recording]       save format [optional; defaults to 'png']
  -o, --output                                                output filename [optional; defaults to stdout]
  -a, --keep-aspect-ratio                                     whether to preserve the aspect ratio [optional; defaults to FALSE]
  -b, --background-color=[black, white, #abccee, #aaa...]     set the background color [optional; defaults to None]
  -u, --unlimited                                             Allow huge SVG files
  --keep-image-data                                           Keep image data
  --no-keep-image-data                                        Don't keep image data
  -v, --version                                               show version information
```

**Comment by bil-elmoussaoui** [comment]
It should be fixed now :P the reason why i added Inkscape support at first, it's because on some distro python svg library was corrupted and not working correctly :(

**Comment by varlesh** [comment]
```
fixing failed with error:
        Traceback (most recent call last):
          File "/opt/Hardcode-Tray/database/scripts/chrome", line 19, in <module>
            pngbytes = svgtopng.convert_svg2bin(icon_for_repl)
          File "/opt/Hardcode-Tray/database/scripts/svgtopng.py", line 75, in convert_svg2bin
            with open('/tmp/hardcode.png', 'rb') as temppng:
        FileNotFoundError: [Errno 2] No such file or directory: '/tmp/hardcode.png'

fixing failed with error:
        Traceback (most recent call last):
          File "/opt/Hardcode-Tray/database/scripts/electron", line 73, in <module>
            pngbytes = svgtopng.convert_svg2bin(icon_for_repl)
          File "/opt/Hardcode-Tray/database/scripts/svgtopng.py", line 75, in convert_svg2bin
            with open('/tmp/hardcode.png', 'rb') as temppng:
        FileNotFoundError: [Errno 2] No such file or directory: '/tmp/hardcode.png'


Done , Thank you for using the Hardcode-Tray fixer!

```

**Comment by varlesh** [comment]
On ubuntu available packages:
python-rsvg
ruby-rsvg2
gir1.2-rsvg-2.0

I'm install all this packages. Or need another?

**Comment by bil-elmoussaoui** [comment]
Pushed a new version again! It has been a long time since i used Ubuntu :( 
On Arch i have those installed
- librsvg
- python2-rsvg
- lib32-librsvg

**Comment by varlesh** [comment]
No errors :)

**Comment by bil-elmoussaoui** [comment]
Perfect! Thanks for reporting ;)

**Comment by edgard** [comment]
yup, back working again since 41d8338, thanks!!

**Comment by bil-elmoussaoui** [comment]
@varlesh where i can get rsvg-convert ? i would like to add the support of it too after the #248 it's so easy to add support of whatever stuff you like ;)

**Comment by varlesh** [comment]
DEB -  `librsvg2-bin`
RPM - `librsvg2-tools`
ARCH -  `librsvg`

**Comment by bil-elmoussaoui** [comment]
Can you open a new issue for that?

**Comment by varlesh** [comment]
i'm? why?

**Comment by varlesh** [comment]
You want replace inkscape to rsvg-convert?

**Comment by bil-elmoussaoui** [comment]
No I will add rsvg-convert and keep inkscape and Cairo

Le 29 déc. 2016 4:23 PM, "Alexey Varfolomeev" <notifications@github.com> a
écrit :

**Comment by bil-elmoussaoui** [comment]
@varlesh rsvg-convert is now on master. You can use it with `--conversion-tool RSVGConvert`
