### ISSUE TITLE
RSVG

### ISSUE THREAD

**Issue by leoheck** [bil-elmoussaoui/Hardcode-Tray#192]
Is this a new requirement to run?

```
Traceback (most recent call last):
  File "/opt/Hardcode-Tray/script.py", line 75, in <module>
    "svgtopng", "%s/database/scripts/svgtopng.py" % absolute_path)
  File "/usr/lib/python3.5/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/opt/Hardcode-Tray//database/scripts/svgtopng.py", line 11, in <module>
    require_version('Rsvg', '2.0')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 102, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Rsvg not available
```

**Comment by bil-elmoussaoui** [comment]
This issue was also fixed on master.. Please follow the wiki guide on how to use the latest git version

**Comment by leoheck** [comment]
Sorry for that! Which guide?

**Comment by bil-elmoussaoui** [comment]
RSVG is used to scale SVG icons in order to support HiDPI icons (Electron icons). If you can't install it, the script will use Inkscape instead  https://github.com/bil-elmoussaoui/Hardcode-Tray/wiki/FAQ#how-to-use-git-version

**Comment by leoheck** [comment]
Ok, then install script don't use git master version. Thank you. Sorry for create many issues.

**Comment by bil-elmoussaoui** [comment]
Nop, but there's an option to update to git version too ;) i use releases to let beginner users have a "stable" version of the script ! Not a problem.
