### ISSUE TITLE
Not worked after last update

### ISSUE THREAD

**Issue by varlesh** [bil-elmoussaoui/Hardcode-Tray#202]
Fresh git-version 1e5917f3480f5221da76cba1959b08cdffbfe883
```
Traceback (most recent call last):
  File "/opt/Hardcode-Tray/script.py", line 512, in <module>
    install(fix_only, icon_path)
  File "/opt/Hardcode-Tray/script.py", line 402, in install
    apps = get_supported_apps(fix_only, custom_path)
  File "/opt/Hardcode-Tray/script.py", line 206, in get_supported_apps
    database_files = listdir(db_folder)
FileNotFoundError: [Errno 2] No such file or directory: 'database/'
alex@dell:~$ 
```

**Comment by varlesh** [comment]
Installed from PPA and apply **--update-git** option. Install path **/opt/Hardcode-Tray** and symlink **/usr/bin/hardcode-tray** (as PKGBUILD on ARCH)

**Comment by bil-elmoussaoui** [comment]
Fixed

**Comment by varlesh** [comment]
Error not showing, but script not working:
```
alex@dell:~$ hardcode-tray -s 22
Welcome to the tray icons hardcoder fixer!
Your indicator icon size is : 22
Your current icon theme is : papirus-arc-dark
Svg to png functions are : Enabled
Applications will be fixed : All
1 - Apply
2 - Revert
Please choose: 1
Applying now..

No apps to fix! Please report on GitHub if this is not the case
alex@dell:~$ 
```
Installed Chrome, Mega, Clementine

**Comment by bil-elmoussaoui** [comment]
Can you go to /opt/hardcode-tray and modify the script.py file. Add after this line https://github.com/bil-elmoussaoui/Hardcode-Tray/blob/master/script.py#L206 `print(database_files)` and paste the output here. 
The script is working perfectly here, just installed the latest git version from AUR and everything works as expected

**Comment by varlesh** [comment]
```
alex@dell:~$ hardcode-tray -s 22
Welcome to the tray icons hardcoder fixer!
Your indicator icon size is : 22
Your current icon theme is : papirus-arc-dark
Svg to png functions are : Enabled
Applications will be fixed : All
1 - Apply
2 - Revert
Please choose: 1
Applying now..

['caprine_ele.json', 'seafile.json', 'grive-tools.json', 'google-music-manager.json', 'trimage.json', 'primeindicator.json', 'hp-printing.json', 'skypeforlinux.json', 'rambox.json', 'dropbox.json', 'keepassx.json', 'anatine.json', 'workrave.json', 'google-chrome.json', 'tomahawk.json', 'indicator-weather.json', 'guake.json', 'catch-indicator.json', 'discord.json', 'scripts', 'ibus-mozc.json', 'nomachine.json', 'spotify.json', 'telegram.json', 'calendar-indicator.json', 'slack.json', 'twitch-indicator.json', 'screencloud.json', 'variety.json', 'teamviewer.json', 'xkbmod-indicator.json', 'overgrive.json', 'pomodoro-indicator.json', 'franz_ele.json', 'wire.json', 'skype.json', 'chromium.json', 'ibus-anthy.json', 'qelectrotech.json', 'museeq.json', 'solaar.json', 'my-weather-indicator.json', 'disper-indicator.json', 'whatsie.json', 'pushbullet-indicator.json', 'cryptfolder-indicator.json', 'messenger_ele.json', 'mintupdate.json', 'google-tasks-indicator.json', 'nylas.json', 'touchpad-indicator.json', 'owncloud.json', 'mumble.json', 'wiznote.json', 'bitcoin.json', 'radiotray.json', 'youtube-indicator.json', 'franz.json', 'stremio.json', 'china-weather.json', 'flareget.json', 'megasync.json', 'caprine.json', 'yd-tools.json', 'hexchat.json', 'sflphone.json', 'clementine.json', 'yum-extender-dnf.json']
No apps to fix! Please report on GitHub if this is not the case
alex@dell:~$ 

```

**Comment by varlesh** [comment]
ls -Rl:
```
.:
итого 28
drwxrwxr-x 3 alex alex  4096 ноя 10 01:25 database
-rwxrwxr-x 1 alex alex   942 ноя 10 01:25 hardcode-tray
-rwxrwxr-x 1 root root 19387 ноя 10 01:52 script.py

./database:
итого 280
-rw-rw-r-- 1 alex alex  751 ноя 10 01:25 anatine.json
-rw-rw-r-- 1 alex alex  404 ноя 10 01:25 bitcoin.json
-rw-rw-r-- 1 alex alex  440 ноя 10 01:25 calendar-indicator.json
-rw-rw-r-- 1 alex alex 1145 ноя 10 01:25 caprine_ele.json
-rw-rw-r-- 1 alex alex  981 ноя 10 01:25 caprine.json
-rw-rw-r-- 1 alex alex  433 ноя 10 01:25 catch-indicator.json
-rw-rw-r-- 1 alex alex  658 ноя 10 01:25 china-weather.json
-rw-rw-r-- 1 alex alex  430 ноя 10 01:25 chromium.json
-rw-rw-r-- 1 alex alex 2655 ноя 10 01:25 clementine.json
-rw-rw-r-- 1 alex alex  471 ноя 10 01:25 cryptfolder-indicator.json
-rw-rw-r-- 1 alex alex  582 ноя 10 01:25 discord.json
-rw-rw-r-- 1 alex alex  365 ноя 10 01:25 disper-indicator.json
-rw-rw-r-- 1 alex alex  566 ноя 10 01:25 dropbox.json
-rw-rw-r-- 1 alex alex  393 ноя 10 01:25 flareget.json
-rw-rw-r-- 1 alex alex  771 ноя 10 01:25 franz_ele.json
-rw-rw-r-- 1 alex alex  711 ноя 10 01:25 franz.json
-rw-rw-r-- 1 alex alex  474 ноя 10 01:25 google-chrome.json
-rw-rw-r-- 1 alex alex  433 ноя 10 01:25 google-music-manager.json
-rw-rw-r-- 1 alex alex  475 ноя 10 01:25 google-tasks-indicator.json
-rw-rw-r-- 1 alex alex  414 ноя 10 01:25 grive-tools.json
-rw-rw-r-- 1 alex alex  457 ноя 10 01:25 guake.json
-rw-rw-r-- 1 alex alex  718 ноя 10 01:25 hexchat.json
-rw-rw-r-- 1 alex alex  401 ноя 10 01:25 hp-printing.json
-rw-rw-r-- 1 alex alex  273 ноя 10 01:25 ibus-anthy.json
-rw-rw-r-- 1 alex alex 1419 ноя 10 01:25 ibus-mozc.json
-rw-rw-r-- 1 alex alex  637 ноя 10 01:25 indicator-weather.json
-rw-rw-r-- 1 alex alex  476 ноя 10 01:25 keepassx.json
-rw-rw-r-- 1 alex alex  831 ноя 10 01:25 megasync.json
-rw-rw-r-- 1 alex alex 1129 ноя 10 01:25 messenger_ele.json
-rw-rw-r-- 1 alex alex  888 ноя 10 01:25 mintupdate.json
-rw-rw-r-- 1 alex alex  394 ноя 10 01:25 mumble.json
-rw-rw-r-- 1 alex alex  656 ноя 10 01:25 museeq.json
-rw-rw-r-- 1 alex alex 5169 ноя 10 01:25 my-weather-indicator.json
-rw-rw-r-- 1 alex alex  740 ноя 10 01:25 nomachine.json
-rw-rw-r-- 1 alex alex  904 ноя 10 01:25 nylas.json
-rw-rw-r-- 1 alex alex  420 ноя 10 01:25 overgrive.json
-rw-rw-r-- 1 alex alex 1369 ноя 10 01:25 owncloud.json
-rw-rw-r-- 1 alex alex  613 ноя 10 01:25 pomodoro-indicator.json
-rw-rw-r-- 1 alex alex  457 ноя 10 01:25 primeindicator.json
-rw-rw-r-- 1 alex alex  492 ноя 10 01:25 pushbullet-indicator.json
-rw-rw-r-- 1 alex alex  416 ноя 10 01:25 qelectrotech.json
-rw-rw-r-- 1 alex alex  339 ноя 10 01:25 radiotray.json
-rw-rw-r-- 1 alex alex 1177 ноя 10 01:25 rambox.json
-rw-rw-r-- 1 alex alex  557 ноя 10 01:25 screencloud.json
drwxrwxr-x 3 alex alex 4096 ноя 10 01:25 scripts
-rw-rw-r-- 1 alex alex 1269 ноя 10 01:25 seafile.json
-rw-rw-r-- 1 alex alex  600 ноя 10 01:25 sflphone.json
-rw-rw-r-- 1 alex alex 3126 ноя 10 01:25 skypeforlinux.json
-rw-rw-r-- 1 alex alex 5206 ноя 10 01:25 skype.json
-rw-rw-r-- 1 alex alex  656 ноя 10 01:25 slack.json
-rw-rw-r-- 1 alex alex 1219 ноя 10 01:25 solaar.json
-rw-rw-r-- 1 alex alex 1584 ноя 10 01:25 spotify.json
-rw-rw-r-- 1 alex alex  425 ноя 10 01:25 stremio.json
-rw-rw-r-- 1 alex alex 1446 ноя 10 01:25 teamviewer.json
-rw-rw-r-- 1 alex alex  852 ноя 10 01:25 telegram.json
-rw-rw-r-- 1 alex alex  445 ноя 10 01:25 tomahawk.json
-rw-rw-r-- 1 alex alex  711 ноя 10 01:25 touchpad-indicator.json
-rw-rw-r-- 1 alex alex  384 ноя 10 01:25 trimage.json
-rw-rw-r-- 1 alex alex  457 ноя 10 01:25 twitch-indicator.json
-rw-rw-r-- 1 alex alex  409 ноя 10 01:25 variety.json
-rw-rw-r-- 1 alex alex  553 ноя 10 01:25 whatsie.json
-rw-rw-r-- 1 alex alex  542 ноя 10 01:25 wire.json
-rw-rw-r-- 1 alex alex  398 ноя 10 01:25 wiznote.json
-rw-rw-r-- 1 alex alex  657 ноя 10 01:25 workrave.json
-rw-rw-r-- 1 alex alex  369 ноя 10 01:25 xkbmod-indicator.json
-rw-rw-r-- 1 alex alex  348 ноя 10 01:25 yd-tools.json
-rw-rw-r-- 1 alex alex  566 ноя 10 01:25 youtube-indicator.json
-rw-rw-r-- 1 alex alex  882 ноя 10 01:25 yum-extender-dnf.json

./database/scripts:
итого 28
-rwxrwxr-x 1 alex alex  777 ноя 10 01:25 chrome
-rwxrwxr-x 1 alex alex 3392 ноя 10 01:25 data_pack.py
-rwxrwxr-x 1 alex alex  739 ноя 10 01:25 dropbox
-rwxrwxr-x 1 alex alex 2826 ноя 10 01:25 electron
drwxr-xr-x 2 root root 4096 ноя 10 01:25 __pycache__
-rwxrwxr-x 1 alex alex  315 ноя 10 01:25 spotify
-rw-rw-r-- 1 alex alex 3150 ноя 10 01:25 svgtopng.py

./database/scripts/__pycache__:
итого 8
-rw-r--r-- 1 root root 2869 ноя 10 01:25 data_pack.cpython-35.pyc
-rw-r--r-- 1 root root 2819 ноя 10 01:25 svgtopng.cpython-35.pyc
```

**Comment by bil-elmoussaoui** [comment]
Try cloning the repo by yourself and just using `sudo -E python3 script.py` ?

**Comment by varlesh** [comment]
worked, but also script create empty folders with some apps
![image](https://cloud.githubusercontent.com/assets/8083855/20158646/a3e512de-a6ec-11e6-8897-cb4b9541ddc3.png)

**Comment by varlesh** [comment]
Why PKGBUILD have wrong install path?:
```
_pkgbase=hardcode-tray-fixer
pkgname=$_pkgbase-git
pkgver=r718.1e5917f
pkgrel=1
pkgdesc="Fixes Hardcoded Tray Icons"
arch=('i686' 'x86_64')
url="https://github.com/bil-elmoussaoui/Hardcode-Tray"
license=('GPL')
provides=("$_pkgbase")
makedepends=('git')
depends=('python' 'python-gobject' 'python-cairosvg' 'librsvg' 'gtk3')
optdepends=('sni-qt-eplus-bzr: patched qt4 sni plugin to enable icon modification' 'inkscape: to convert svg to png with inkscape')
optdepends_x86_64=('lib32-sni-qt-eplus-bzr: 32-bit patched qt4 sni plugin to enable icon modification')
source=("$pkgname::git://github.com/bil-elmoussaoui/Hardcode-Tray" "hardcode-tray-fixer.sh")
sha256sums=('SKIP'
            '2df8935eae4644ffc29554a067fdc3fb3ba61b74ae6135dad4154a9c1c45c4a9')

pkgver() {
  cd "$srcdir/$pkgname"
  ( set -o pipefail
    git describe --long 2>/dev/null | sed 's/\([^-]*-g\)/r\1/;s/-/./g' ||
    printf "r%s.%s" "$(git rev-list --count HEAD)" "$(git rev-parse --short HEAD)"
  )
}

package() {
  install -Dm755 "$srcdir/hardcode-tray-fixer.sh" "$pkgdir/usr/bin/hardcode-tray"
  install -Dm755 "$srcdir/$pkgname/script.py" "$pkgdir/opt/$_pkgbase/script.py"
  install -d "$pkgdir/opt/$_pkgbase"
  cp -r "$srcdir/$pkgname/database" "$pkgdir/opt/$_pkgbase"
}
```
install -Dm755 "$srcdir/$pkgname/script.py" "$pkgdir/opt/$_pkgbase/script.py"
_pkgbase=**hardcode-tray-fixer**

**PATH=/opt/hardcode-tray-fixer**

**Comment by bil-elmoussaoui** [comment]
I'am not the maintainer of AUR package. report that upstream please :) 
Which sni-qt applications folders were created? those applications are not installed in your case?

**Comment by varlesh** [comment]
https://github.com/bil-elmoussaoui/Hardcode-Tray/blob/master/hardcode-tray
`sudo -E python3 /opt/Hardcode-Tray/script.py "$@"`

**Comment by bil-elmoussaoui** [comment]
Well, this line is the one that must be used if you install hardcode-tray using the script i provide in the repo. The installation method in the PKGBUILD does not follow any of that; so it's up to the maintainer of the AUR package to change that..
And i fixed the latest issue with qt empty folders being created even if the application is not installed

**Comment by varlesh** [comment]
>I'am not the maintainer of AUR package. report that upstream please :) 

Maintaner have account on github?

Which sni-qt applications folders were created? those applications are not installed in your case?

I'm have megasync and clementine only. Other apps not installed:

- bitcoin-qt
- flareget
- mumble
- museeq
- MusicManager
- owncloud
- python2.7
- qelectrotech
- screencloud
- seafile-applet
- skype
- tomahawk
- TVGuiDelegate
- WizNote

**Comment by bil-elmoussaoui** [comment]
The maintainer of AUR package is @edgard. And as i said before, this issue is now fixed on master

**Comment by varlesh** [comment]
Ok.
Why not worked from /opt/Hardcode-Tray?

**Comment by bil-elmoussaoui** [comment]
Hardcode-Tray in the opt folder must be outdated as you're using the AUR package which does not download the source in the same location; try running `hardcode-tray --update-git`

**Comment by varlesh** [comment]
i'm use ubuntu 16.04 (KDE Neon)

**Comment by varlesh** [comment]
broken script hardcode-tray, because after `--update-git` and run `sudo -E python3 /opt/Hardcode-Tray/script.py`
All worked

**Comment by varlesh** [comment]
no!!! Need cd directory where available database/
Not working:
`sudo -E python3 /opt/Hardcode-Tray/script.py`
Working:
```
cd /opt/Hardcode-Tray/
sudo -E python3 script.py
```

**Comment by bil-elmoussaoui** [comment]
It's normal that running the first command won't make the script work. As the absolute path detected will be the folder you're in, so the python code won't be able to detect the database folder.

**Comment by varlesh** [comment]
need fix script, for example:
```
        exit 0 ;;
    *)
       cd /opt/Hardcode-Tray
        sudo -E python3 /opt/Hardcode-Tray/script.py "$@"
esac
```

**Comment by bil-elmoussaoui** [comment]
@varlesh Are you sure? everything works fine in my case... 
@wa4557 can you try so we can have a third result ?

**Comment by varlesh** [comment]
@bil-elmoussaoui yes, because needed for packages (ARCH and DEB) Exit to home directory and run `sudo -E python3 /path_to_folder/script.py` - this's not worked, because script not seen database

**Comment by bil-elmoussaoui** [comment]
I did those changes on master

**Comment by varlesh** [comment]
All worked now!
When will be new release?

**Comment by bil-elmoussaoui** [comment]
I will work on nwjs issues #157 & #152 tomorrow! i will push a new version just after that. So maybe tomorrow evening or this weekend

**Comment by varlesh** [comment]
Ok, i'm update PPA after next stable release. Thx you:)

**Comment by edgard** [comment]
The name is "hardcoded-tray-fixer" on Arch because when I adopted it from the previous maintainer on AUR it was already named like that. To change that we would need to create a new package and delete the older one, which will break for previous users.
