### ISSUE TITLE
Rrevert option not worked

### ISSUE THREAD

**Issue by varlesh** [bil-elmoussaoui/Hardcode-Tray#223]
Git-version: 693c13c5cf77a0f1fb6612f3db1631d4c9551c30
log:
```
alex@dell:~$ hardcode-tray -s 22
Welcome to the tray icons hardcoder fixer!
Your indicator icon size is : 22
Your current icon theme is : Papirus-Dark-GTK
Svg to png functions are : Enabled
Applications will be fixed : All
1 - Apply
2 - Revert
Please choose: 2
Reverting now..

Traceback (most recent call last):
  File "script.py", line 550, in <module>
    reinstall(fix_only, icon_path)
  File "script.py", line 415, in reinstall
    print("%s -- reverted" % apps[app]["name"])
TypeError: list indices must be integers or slices, not dict
alex@dell:~$ 
```

**Comment by bil-elmoussaoui** [comment]
Fixed

**Comment by varlesh** [comment]
Now it's ok! You are awesome :+1:
