### ISSUE TITLE
Script failure when dropbox is not installed

### ISSUE THREAD

**Issue by dslul** [bil-elmoussaoui/Hardcode-Tray#29]
Here is the error:

Welcome to the tray icons hardcoder fixer! 

Copying now..

Traceback (most recent call last):
  File "script.py", line 160, in <module>
    copy_files()
  File "script.py", line 106, in copy_files
    apps = csv_to_dic()
  File "script.py", line 94, in csv_to_dic
    row[1] = dropbox_folder(row[1])
  File "script.py", line 79, in dropbox_folder
    sub_dirs = get_subdirs(dirs[0])
  File "script.py", line 50, in get_subdirs
    dirs = os.listdir(d)
FileNotFoundError: [Errno 2] File o directory non esistente: '/home/daniele/.dropbox-dist/'

I solved (just in my case) by removing lines 93 and 94, however i cannot send you a proper patch since a know nothing about python at the moment.

**Comment by bil-elmoussaoui** [comment]
I pushed a new commit, can you try this now?

**Comment by dslul** [comment]
It doesn't work:

Welcome to the tray icons hardcoder fixer! 

Copying now..

Traceback (most recent call last):
  File "script.py", line 163, in <module>
    copy_files()
  File "script.py", line 109, in copy_files
    apps = csv_to_dic()
  File "script.py", line 97, in csv_to_dic
    row[1] = dropbox_folder(row[1])
  File "script.py", line 83, in dropbox_folder
    sub_dirs.sort()
AttributeError: 'NoneType' object has no attribute 'sort'

**Comment by bil-elmoussaoui** [comment]
This should be fixed now

**Comment by dslul** [comment]
Still nothing:

Welcome to the tray icons hardcoder fixer! 

Copying now..

Traceback (most recent call last):
  File "script.py", line 166, in <module>
    copy_files()
  File "script.py", line 112, in copy_files
    apps = csv_to_dic()
  File "script.py", line 101, in csv_to_dic
    if is_dir(row[1]+"/"):#check if the folder exists
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

**Comment by bil-elmoussaoui** [comment]
Can you try again? :) This is not the best way to fix it, but i will update the script when i will finish my finals!

**Comment by dslul** [comment]
Ok, now it works!

**Comment by bil-elmoussaoui** [comment]
Thank you for reporting this!
