### ISSUE TITLE
Error for zip files

### ISSUE THREAD

**Issue by wa4557** [bil-elmoussaoui/Hardcode-Tray#295]
something wrong with the backup directory? (Just a quick reminder I can elaborate further later)

Traceback (most recent call last):
  File "script.py", line 320, in <module>
    install(fix_only, icon_path)
  File "script.py", line 205, in install
    app.install()
  File "/opt/Hardcode-Tray/modules/applications/zip.py", line 63, in install
    self.install_symlinks()
TypeError: install_symlinks() missing 1 required positional argument: 'back_dir'

**Comment by bil-elmoussaoui** [comment]
Ah jts an easy fix ! I will do that right now
