### ISSUE TITLE
FileNotFoundError:

### ISSUE THREAD

**Issue by KottV** [bil-elmoussaoui/Hardcode-Tray#299]
With latest git or latest release i got:
```

kv@Kot:/> hardcode-tray --theme Papirus-Light
Invalid MIT-MAGIC-COOKIE-1 keyUnable to init server: Could not connect: Connection refused
Invalid MIT-MAGIC-COOKIE-1 keyUnable to init server: Could not connect: Connection refused
Traceback (most recent call last):
  File "script.py", line 53, in <module>
    THEMES_LIST = get_list_of_themes()
  File "/opt/Hardcode-Tray/modules/utils.py", line 244, in get_list_of_themes
    sub_dirs = listdir(icon_path)
FileNotFoundError: [Errno 2] No such file or directory: 'home/kv/.local/share/icons/'
```
No lead slash in home path. I "fixed" this in script, but then got:
I think this is error in my current install (last openSUSE TW update broke smth in python)
```
kv@Kot:/> hardcode-tray --theme Papirus-Light
Invalid MIT-MAGIC-COOKIE-1 keyUnable to init server: Could not connect: Connection refused
Invalid MIT-MAGIC-COOKIE-1 keyUnable to init server: Could not connect: Connection refused

(script.py:11219): Gtk-CRITICAL **: gtk_icon_theme_get_for_screen: assertion 'GDK_IS_SCREEN (screen)' failed
Welcome to the tray icons hardcoder fixer!
Your indicator icon size is : 22
Your current icon theme is : Papirus-Light
Svg to png functions are : Enabled
Conversion tool : Inkscape
Applications will be fixed : All
1 - Apply
2 - Revert
Please choose: 1
Applying now..

Traceback (most recent call last):
  File "script.py", line 320, in <module>
    install(fix_only, icon_path)
  File "script.py", line 199, in install
    apps = get_supported_apps(fix_only, custom_path)
  File "script.py", line 140, in get_supported_apps
    custom_path, is_only)
  File "/opt/Hardcode-Tray/modules/data.py", line 51, in __init__
    self.read()
  File "/opt/Hardcode-Tray/modules/data.py", line 87, in read
    self.get_app_icons()
  File "/opt/Hardcode-Tray/modules/data.py", line 99, in get_app_icons
    self.default_icon_size)
  File "/opt/Hardcode-Tray/modules/icon.py", line 44, in __init__
    self.read()
  File "/opt/Hardcode-Tray/modules/icon.py", line 63, in read
    orig_icon = self.icon_data["original"]
TypeError: list indices must be integers or slices, not str

```

**Comment by bil-elmoussaoui** [comment]
As you can see here https://github.com/bil-elmoussaoui/Hardcode-Tray/blob/master/modules/const.py#L32
It's impossible that your home path does not have `/` at the beginning of it. 
Either you're using an old version of the script or something is broken in your system. 

Can you try uninstalling the script and installing it again ? https://github.com/bil-elmoussaoui/Hardcode-Tray#manual-install This way you will have the git version!

**Comment by KottV** [comment]
i agree, something is broken =/

**Comment by bil-elmoussaoui** [comment]
Anyway, it seems that Gtk is not able to detect something `(script.py:11219): Gtk-CRITICAL **: gtk_icon_theme_get_for_screen: assertion 'GDK_IS_SCREEN (screen)' failed` has nothing to do with my code. See the error here https://stackoverflow.com/questions/15270251/gtk-init-failed-unexpected

What's your python version? Same for Gtk version?

**Comment by KottV** [comment]
python 3.5.1
gtk 2.24.31 and 3.22.6

it's definitely my python issue, cause bzr tool is broken too now

**Comment by KottV** [comment]
I have to reopen this issue.
Problem was in python2 installation. All python3 programs works well, except hardcode-tray:
```
kv@Kot:~/src/Hardcode-Tray> ./hardcode-tray --theme Papirus-Light
[sudo] ?????? ??? root: 
Invalid MIT-MAGIC-COOKIE-1 keyUnable to init server: Could not connect: Connection refused
Invalid MIT-MAGIC-COOKIE-1 keyUnable to init server: ?? ??????? ???????????? ?: Connection refused

(script.py:29613): Gtk-CRITICAL **: gtk_icon_theme_get_for_screen: assertion 'GDK_IS_SCREEN (screen)' failed
Welcome to the tray icons hardcoder fixer!
Your indicator icon size is : 22
Your current icon theme is : Papirus-Light
Svg to png functions are : Enabled
Conversion tool : Inkscape
Applications will be fixed : All
1 - Apply
2 - Revert
Please choose: 1
Applying now..

Traceback (most recent call last):
  File "script.py", line 320, in <module>
    install(fix_only, icon_path)
  File "script.py", line 199, in install
    apps = get_supported_apps(fix_only, custom_path)
  File "script.py", line 140, in get_supported_apps                                                                                                                                                                                                           
    custom_path, is_only)                                                                                                                                                                                                                                     
  File "/opt/Hardcode-Tray/modules/data.py", line 51, in __init__                                                                                                                                                                                             
    self.read()                                                                                                                                                                                                                                               
  File "/opt/Hardcode-Tray/modules/data.py", line 87, in read                                                                                                                                                                                                 
    self.get_app_icons()                                                                                                                                                                                                                                      
  File "/opt/Hardcode-Tray/modules/data.py", line 99, in get_app_icons                                                                                                                                                                                        
    self.default_icon_size)                                                                                                                                                                                                                                   
  File "/opt/Hardcode-Tray/modules/icon.py", line 44, in __init__                                                                                                                                                                                             
    self.read()                                                                                                                                                                                                                                               
  File "/opt/Hardcode-Tray/modules/icon.py", line 63, in read                                                                                                                                                                                                 
    orig_icon = self.icon_data["original"]
TypeError: list indices must be integers or slices, not str

```

**Comment by bil-elmoussaoui** [comment]
Can you try adding `--debug` flag and paste the output here?

**Comment by KottV** [comment]
```
Applying now..

[DEBUG] - 2017-01-23 14:34:28 - new application Bitcoin path : home/kv/.local/share/sni-qt/icons/bitcoin-qt/22/
[DEBUG] - 2017-01-23 14:34:28 - new application Clementine path : home/kv/.local/share/sni-qt/icons/clementine/22/
[DEBUG] - 2017-01-23 14:34:29 - new application Dropbox path : home/kv/.dropbox-dist/
[DEBUG] - 2017-01-23 14:34:29 - new application Dropbox path : home/kv/.dropbox-dist/{dropbox}/images/hicolor/16x16/status/
[DEBUG] - 2017-01-23 14:34:29 - new application Flarget path : home/kv/.local/share/sni-qt/icons/flareget/22/
[DEBUG] - 2017-01-23 14:34:29 - new application Google Music Manager path : home/kv/.local/share/sni-qt/icons/MusicManager/22/
[DEBUG] - 2017-01-23 14:34:29 - new application Hangouts path : home/kv/.config/chromium/Default/Extensions/nckgahadagoaajjgafhacjanaoiihapd/
[DEBUG] - 2017-01-23 14:34:29 - new application Hangouts path : home/kv/.config/google-chrome/Default/Extensions/nckgahadagoaajjgafhacjanaoiihapd/
[DEBUG] - 2017-01-23 14:34:29 - new application Hangouts path : home/kv/.config/google-chrome-beta/Default/Extensions/nckgahadagoaajjgafhacjanaoiihapd/
[DEBUG] - 2017-01-23 14:34:29 - new application Hangouts path : home/kv/.config/google-chrome-unstable/Default/Extensions/nckgahadagoaajjgafhacjanaoiihapd/
[DEBUG] - 2017-01-23 14:34:29 - new application Hangouts path : home/kv/.config/vivaldi/Default/Extensions/nckgahadagoaajjgafhacjanaoiihapd/
[DEBUG] - 2017-01-23 14:34:29 - new application Hangouts path : home/kv/.config/vivaldi-beta/Default/Extensions/nckgahadagoaajjgafhacjanaoiihapd/
[DEBUG] - 2017-01-23 14:34:29 - new application Hangouts path : home/kv/.config/vivaldi-snapshot/Default/Extensions/nckgahadagoaajjgafhacjanaoiihapd/
[DEBUG] - 2017-01-23 14:34:29 - new application Hangouts path : home/kv/.config/chromium/Default/Extensions/nckgahadagoaajjgafhacjanaoiihapd/2017.110.418.2_0/images_5/
[DEBUG] - 2017-01-23 14:34:29 - new application Hangouts path : home/kv/.config/google-chrome/Default/Extensions/nckgahadagoaajjgafhacjanaoiihapd/2017.110.418.2_00/images_5/
[DEBUG] - 2017-01-23 14:34:29 - new application Hangouts path : home/kv/.config/google-chrome-beta/Default/Extensions/nckgahadagoaajjgafhacjanaoiihapd/2017.110.418.2_0/images_5/
[DEBUG] - 2017-01-23 14:34:29 - new application Hangouts path : home/kv/.config/google-chrome-unstable/Default/Extensions/nckgahadagoaajjgafhacjanaoiihapd/2017.110.418.2_0/images_5/
[DEBUG] - 2017-01-23 14:34:29 - new application Hangouts path : home/kv/.config/vivaldi/Default/Extensions/nckgahadagoaajjgafhacjanaoiihapd/2017.110.418.2_0/images_5/
[DEBUG] - 2017-01-23 14:34:29 - new application Hangouts path : home/kv/.config/vivaldi-beta/Default/Extensions/nckgahadagoaajjgafhacjanaoiihapd/2017.110.418.2_0/images_5/
[DEBUG] - 2017-01-23 14:34:29 - new application Hangouts path : home/kv/.config/vivaldi-snapshot/Default/Extensions/nckgahadagoaajjgafhacjanaoiihapd/2017.110.418.2_0/images_5/
[DEBUG] - 2017-01-23 14:34:29 - new application Hexchat path : home/kv/.config/hexchat/icons/
[DEBUG] - 2017-01-23 14:34:29 - new application HP Printer path : home/kv/.local/share/sni-qt/icons/python2.7/22/
[DEBUG] - 2017-01-23 14:34:29 - new application Megasync path : home/kv/.local/share/sni-qt/icons/megasync/22/
[DEBUG] - 2017-01-23 14:34:29 - new application Mumble path : home/kv/.local/share/sni-qt/icons/mumble/22/
[DEBUG] - 2017-01-23 14:34:29 - new application Museeq path : home/kv/.local/share/sni-qt/icons/museeq/22/
[DEBUG] - 2017-01-23 14:34:29 - new application OwnCloud path : home/kv/.local/share/sni-qt/icons/owncloud/22/
[DEBUG] - 2017-01-23 14:34:29 - new application QElectroTech path : home/kv/.local/share/sni-qt/icons/qelectrotech/22/
[DEBUG] - 2017-01-23 14:34:29 - new application RescueTime path : home/kv/.local/share/sni-qt/icons/rescuetime/22/
[DEBUG] - 2017-01-23 14:34:29 - new application ScreenCloud path : home/kv/.local/share/sni-qt/icons/screencloud/22/
[DEBUG] - 2017-01-23 14:34:29 - new application Seafile path : home/kv/.local/share/sni-qt/icons/seafile-applet/22/
[DEBUG] - 2017-01-23 14:34:29 - new application Skype path : home/kv/.local/share/sni-qt/icons/skype/22/
[DEBUG] - 2017-01-23 14:34:29 - new application Steam path : home/kv/.steam/
[DEBUG] - 2017-01-23 14:34:29 - new application Teamviewer path : home/kv/.local/share/sni-qt/icons/TVGuiDelegate/22/
[DEBUG] - 2017-01-23 14:34:29 - new application Telegram path : home/kv/.TelegramDesktop/Telegram
[DEBUG] - 2017-01-23 14:34:29 - new application Telegram path : home/kv/.local/share/TelegramDesktop/Telegram
[DEBUG] - 2017-01-23 14:34:29 - new application Telegram path : home/kv/.TelegramDesktop/tdata/ticons/
[DEBUG] - 2017-01-23 14:34:29 - new application Telegram path : home/kv/.local/share/TelegramDesktop/tdata/ticons/
[DEBUG] - 2017-01-23 14:34:29 - new application Tomahawk path : home/kv/.local/share/sni-qt/icons/tomahawk/22/
Traceback (most recent call last):
  File "script.py", line 320, in <module>
    install(fix_only, icon_path)
  File "script.py", line 199, in install
    apps = get_supported_apps(fix_only, custom_path)
  File "script.py", line 140, in get_supported_apps
    custom_path, is_only)
  File "/opt/Hardcode-Tray/modules/data.py", line 51, in __init__
    self.read()
  File "/opt/Hardcode-Tray/modules/data.py", line 87, in read
    self.get_app_icons()
  File "/opt/Hardcode-Tray/modules/data.py", line 99, in get_app_icons
    self.default_icon_size)
  File "/opt/Hardcode-Tray/modules/icon.py", line 44, in __init__
    self.read()
  File "/opt/Hardcode-Tray/modules/icon.py", line 63, in read
    orig_icon = self.icon_data["original"]
TypeError: list indices must be integers or slices, not str

```

**Comment by bil-elmoussaoui** [comment]
Fixes that right now! i forgot to update the Tomahawk json file to follow the latest version of the code! Sorry for that; Just update to git version `hardcode-tray --update-git` and it should work fine :)

**Comment by KottV** [comment]
Unfortunately same error (

**Comment by bil-elmoussaoui** [comment]
Can you do as i proposed just before? this way i can know which application database is causing this.

**Comment by KottV** [comment]
Damn, my fault (i ran from my ~/src dir, while scripts still looking at /opt). Sorry, this error is fixed.
But i have nice new one :)

**Comment by bil-elmoussaoui** [comment]
Just open a new issue and i will fix it ;)
