### ISSUE TITLE
ls: cannot access 'xprop -root _DT_SAVE_MODE'

### ISSUE THREAD

**Issue by MarekAG** [bil-elmoussaoui/Hardcode-Tray#323]
### Specifications
- Hardcode-Tray version : `3.5.2.1~725~ubuntu16.04.1`
- Distribution : `Ubuntu 16.04 x86_64 Linux 4.8.0-39-generic`
- Sni-qt version: `0.2.7+20161212~10~ubuntu16.04.1` 

### Expected behavior and actual behavior

Hi, I just installed hardcode-tray and it seems that it is not working at all. Here is the stack trace (of course I typed proper sudo password):

```bash
hardcode-tray --apply
[sudo] password for marekag: 
ls: cannot access 'xprop -root _DT_SAVE_MODE': No such file or directory
Traceback (most recent call last):
  File "script.py", line 26, in <module>
    from modules.parser import Parser, ArgsParser, CONVERSION_TOOLS
  File "/opt/Hardcode-Tray/modules/parser.py", line 27, in <module>
    from modules.const import ARCH, USERHOME, DESKTOP_ENV
  File "/opt/Hardcode-Tray/modules/const.py", line 39, in <module>
    DESKTOP_ENV = detect_de()
  File "/opt/Hardcode-Tray/modules/tools.py", line 53, in detect_de
    if "xfce" in out:
TypeError: argument of type 'NoneType' is not iterable
```

Everything is up-to-date I think:

```bash
sudo apt install sni-qt sni-qt:i386 hardcode-tray
Reading package lists... Done
Building dependency tree       
Reading state information... Done
sni-qt is already the newest version (0.2.7+20161212~10~ubuntu16.04.1).
hardcode-tray is already the newest version (3.5.2.1~725~ubuntu16.04.1).
sni-qt:i386 is already the newest version (0.2.7+20161212~10~ubuntu16.04.1).
```

### Steps to reproduce the problem
1. Open terminal
2. Try to run "hardcode-tray"

**Comment by bil-elmoussaoui** [comment]
Do you have xprop installed? It's available on your package system. Just run `sudo apt install xprop` 
And try again! 
Thanks for reporting

**Comment by MarekAG** [comment]
Thanks for so fast feedback.

Should xprop be in ubuntu repos?

```bash
sudo apt install xprop
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package xprop
```

but:
```
xprop --version
```

gives me:

```
usage:  xprop [-options ...] [[format [dformat]] atom] ...

where options include:
    -grammar                       print out full grammar for command line
    -display host:dpy              the X server to contact
    -id id                         resource id of window to examine
    -name name                     name of window to examine
    -font name                     name of font to examine
    -remove propname               remove a property
    -set propname value            set a property to a given value
    -root                          examine the root window
    -len n                         display at most n bytes of any property
    -notype                        do not display the type field
    -fs filename                   where to look for formats for properties
    -frame                         don't ignore window manager frames
    -f propname format [dformat]   formats to use for property of given name
    -spy                           examine window properties forever
```

**Comment by bil-elmoussaoui** [comment]
Thanks! I will put an attempt to fix this, and i will tell you how to upgrade to the master branch in order to test. Is that fine for you? it won't break anything on your system :)

**Comment by bil-elmoussaoui** [comment]
Should be fixed, just run `hardcode-tray --update-git` and run the script again

**Comment by MarekAG** [comment]
Just WOW. I didn't expect so fast fix. Now everything works great. Thanks a lot!

**Comment by bil-elmoussaoui** [comment]
My pleasure ;) Thanks for reporting! Don't hesitate to open any new issues/recommendations/requests in the future!
