### ISSUE TITLE
 local variable 'conversion_tool' referenced before assignment

### ISSUE THREAD

**Issue by wa4557** [bil-elmoussaoui/Hardcode-Tray#358]
### Specifications
- Hardcode-Tray version : latest
- Distribution : `Ubuntu`

### Steps to reproduce the problem
1. Run the script
2. First thing you see is 

```Traceback (most recent call last):
  File "hardcode-tray.py", line 93, in <module>
    print("Conversion tool : {0}".format(App.svg()))
  File "/opt/Hardcode-Tray/src/app.py", line 155, in svg
    if conversion_tool:
UnboundLocalError: local variable 'conversion_tool' referenced before assignment
```

I'm using a config file, that specifies the conversion_tool

**Comment by bil-elmoussaoui** [comment]
I have already fixed that issue on my local machine, i will push that fix in an hour :+1:

**Comment by bil-elmoussaoui** [comment]
Fixed on master

**Comment by wa4557** [comment]
Nope. Now it tells me:

```
Traceback (most recent call last):
  File "hardcode-tray.py", line 87, in <module>
    if not isinstance(App.theme(), dict):
  File "/opt/Hardcode-Tray/src/app.py", line 227, in theme
    source = Gio.SettingsSchemaSource.get_default()
NameError: name 'Gio' is not defined
```

**Comment by bil-elmoussaoui** [comment]
You must be missing a dependency then (that we should include on the ppa ofc) :P 
Because Gio is imported at the beginning of the file

**Comment by wa4557** [comment]
Ok it seems that the `--update` flag is broken. manually reinstalling it works. Is it possible that it doesn't update the right files (you changed the names of quite a few)

**Comment by bil-elmoussaoui** [comment]
Yeah, it doesn't work you should update manually or reuse the install.sh in order to get everything to work with the latest version

**Comment by wa4557** [comment]
And this one as well ;)

```
Traceback (most recent call last):
  File "hardcode-tray.py", line 122, in <module>
    App.execute(action)
  File "/opt/Hardcode-Tray/src/app.py", line 115, in execute
    app.install()
  File "/opt/Hardcode-Tray/src/decorators.py", line 47, in wrapper
    func(app)
  File "/opt/Hardcode-Tray/src/modules/applications/application.py", line 124, in install
    self.execute(Action.APPLY)
  File "/opt/Hardcode-Tray/src/modules/applications/extract.py", line 37, in execute
    self.extract(icon_path)
  File "/opt/Hardcode-Tray/src/modules/applications/zip.py", line 50, in extract
    with ZipFile(icon_path + self.binary) as zip_object:
TypeError: unsupported operand type(s) for +: 'Path' and 'str'
```

**Comment by bil-elmoussaoui** [comment]
@wa4557 Both issues are fixed on master

**Comment by wa4557** [comment]
Another one:

running:

```hardcode-tray --clear-cache```

gives:

```
Welcome to the tray icons hardcoder fixer!
Traceback (most recent call last):
  File "hardcode-tray.py", line 85, in <module>
    print("Your indicator icon size is : {0}".format(App.icon_size()))
  File "/opt/Hardcode-Tray/src/app.py", line 193, in icon_size
    if App.config().get("icons"):
  File "/opt/Hardcode-Tray/src/app.py", line 143, in config
    App._config = load(data)
  File "/usr/lib/python3.5/json/__init__.py", line 268, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by wa4557** [comment]
Once more running the app gives:

```
Traceback (most recent call last):
  File "hardcode-tray.py", line 121, in <module>
    App.execute(action)
  File "/opt/Hardcode-Tray/src/app.py", line 106, in execute
    app.install()
  File "/opt/Hardcode-Tray/src/decorators.py", line 60, in wrapper
    func(app)
  File "/opt/Hardcode-Tray/src/modules/applications/application.py", line 125, in install
    self.execute(Action.APPLY)
  File "/opt/Hardcode-Tray/src/modules/applications/binary.py", line 54, in execute
    self.install_icon(icon, icon_path)
  File "/opt/Hardcode-Tray/src/modules/applications/pak.py", line 67, in install_icon
    self.set_icon(icon, icon_path, pngbytes, True)
  File "/opt/Hardcode-Tray/src/modules/applications/pak.py", line 56, in set_icon
    self.backup.file(str(icon_name), self.pak.resources[icon_name])
KeyError: 8003
```

**Comment by bil-elmoussaoui** [comment]
Your json config file is broken. But i wll add an exception for that  (first issue)

**Comment by bil-elmoussaoui** [comment]
Both issues fixed on master

**Comment by wa4557** [comment]
How is that broken?

```
{
    "conversion-tool": "Inkscape",
    "backup-ignore": true
}
```

**Comment by bil-elmoussaoui** [comment]
Well, it's what the output shows :/ Do you still get the same error?

**Comment by wa4557** [comment]
Nope your fix fixed that, not exactly sure why though. clean-cache doesn't delete the folder though

**Comment by bil-elmoussaoui** [comment]
Does it remove the subfolders? or at least the contents? 
to be sure that everything works, check the log files /tmp/Hardcode-Tray/

**Comment by wa4557** [comment]
Nothing in the logfiles. The folders with the dates are still there, but at least they are empty :)

**Comment by wa4557** [comment]
Everything looks good now :+1:

**Comment by bil-elmoussaoui** [comment]
The folders were created automatically because i was missing a condition, but should be fixed now :+1:

**Comment by wa4557** [comment]
Ha I got another one :)

```
Traceback (most recent call last):
  File "hardcode-tray.py", line 121, in <module>
    App.execute(action)
  File "/opt/Hardcode-Tray/src/app.py", line 106, in execute
    app.install()
  File "/opt/Hardcode-Tray/src/decorators.py", line 61, in wrapper
    func(app)
  File "/opt/Hardcode-Tray/src/modules/applications/application.py", line 125, in install
    self.execute(Action.APPLY)
  File "/opt/Hardcode-Tray/src/modules/applications/extract.py", line 44, in execute
    self.install_icon(icon, self.tmp_data)
  File "/opt/Hardcode-Tray/src/decorators.py", line 35, in wrapper
    func(application, icon, icon_path)
  File "/opt/Hardcode-Tray/src/modules/applications/application.py", line 139, in install_icon
    output_icon = icon_path.append(icon.original)
AttributeError: 'str' object has no attribute 'append'
```

**Comment by bil-elmoussaoui** [comment]
Hmm i know what causes this, i will see how i can fix it :)

**Comment by bil-elmoussaoui** [comment]
Fixed
