### ISSUE TITLE
PPA missing depend (for non-GTK DE's)

### ISSUE THREAD

**Issue by varlesh** [bil-elmoussaoui/Hardcode-Tray#384]
@wa4557 Hi Andreas )
On KDE Neon hardcode-tray not worked, because need depend `gir1.2-gtk-3.0`. Please add this package for Dependencies on DEBIAN/Control.
See log:
```
Traceback (most recent call last):
  File "hardcode-tray.py", line 25, in <module>
    from src.app import App
  File "/opt/Hardcode-Tray/src/app.py", line 32, in <module>
    from src.modules.config.arguments import ArgumentsConfig
  File "/opt/Hardcode-Tray/src/modules/config/arguments.py", line 26, in <module>
    from src.modules.theme import Theme
  File "/opt/Hardcode-Tray/src/modules/theme.py", line 24, in <module>
    require_version("Gtk", "3.0")
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 102, in require_version
    raise ValueError('Namespace %s not available' % namespace)
```

**Comment by wa4557** [comment]
Will do

**Comment by varlesh** [comment]
Thx!

**Comment by wa4557** [comment]
Done
