### ISSUE TITLE
Ask for root privileges only when needed.

### ISSUE THREAD

**Issue by bil-elmoussaoui** [bil-elmoussaoui/Hardcode-Tray#397]
For now, we do ask for root privileges even when it's not needed (cleaning the cache? installing only apps that store their icon on the home folder like Telegram, Hexchat, or Qt apps).

The best way to handle this is to run the script as a normal user and use pkexec(PolicyKit) to do the root stuff for us. 
PolicyKit is created by FreeDesktop. So it should be supported on all the Linux distro out there https://www.freedesktop.org/software/polkit/docs/latest/

**Comment by Foggalong** [comment]
Yeah, this really needs fixing 😜 

```bash
josh@brain:~$ hardcode-tray --version
You need to have root privileges to run the script.
Please try again, this time using 'sudo'. Exiting.
```

**Comment by Foggalong** [comment]
The handling of this actually seems to have gotten worse since this issue was last reported; the script no longer even exits gracefully when ``--version` is used without root.

```
s1985194@migs:~$ hardcode-tray -v
Traceback (most recent call last):
  File "/usr/bin/hardcode-tray", line 40, in <module>
    from HardcodeTray.app import App
  File "/usr/lib/python3.6/site-packages/HardcodeTray/app.py", line 25, in <module>
    from HardcodeTray.const import DB_FOLDER
  File "/usr/lib/python3.6/site-packages/HardcodeTray/const.py", line 39, in <module>
    DESKTOP_ENV = detect_de(DE)
  File "/usr/lib/python3.6/site-packages/HardcodeTray/tools.py", line 41, in detect_de
    Logger.debug("DE not detected.")
  File "/usr/lib/python3.6/site-packages/HardcodeTray/modules/log.py", line 70, in debug
    Logger.get_default().debug(msg)
  File "/usr/lib/python3.6/site-packages/HardcodeTray/modules/log.py", line 50, in get_default
    with open(tmp_file, 'w') as tmp_obj:
PermissionError: [Errno 13] Permission denied: '/tmp/Hardcode-Tray/2020-12-28 14:59:48.log'
```
