### ISSUE TITLE
telegram

### ISSUE THREAD

**Issue by dimuravyev** [bil-elmoussaoui/Hardcode-Tray#89]
cat i use it for telegram in ubuntu unity 14.04?

**Comment by bil-elmoussaoui** [comment]
Are you talking about [Telegram Desktop](https://desktop.telegram.org/)?

**Comment by dimuravyev** [comment]
yes

**Comment by bil-elmoussaoui** [comment]
Yes, you can :) Just run the script; it's will autodetect the hardcoded applications that we support.Can you confirm that everything's working fine in your case?

**Comment by dimuravyev** [comment]
```
$ sudo -E python3 script.py
```
```
Welcome to the tray icons hardcoder fixer!
Your indicator icon size is : 22
Your current icon theme is : Numix-Light
1 - Install
2 - Reinstall
Please choose: 1
Installing now..

Traceback (most recent call last):
  File "script.py", line 404, in <module>
    install()
  File "script.py", line 283, in install
    apps = get_apps_informations()
  File "script.py", line 175, in get_apps_informations
    real_icons = get_correct_chrome_icons(app,icons[0][3])
  File "script.py", line 133, in get_correct_chrome_icons
    default_content = open(images_dir+ default_icon + ".png", "rb").read()
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/Hardcode-Tray/database/images/chromium/notification.png'
```

**Comment by bil-elmoussaoui** [comment]
I fixed the issue, clone the repo and try again

**Comment by wa4557** [comment]
Have you cloned the whole repo or just downloaded the script?

dimuravyev <notifications@github.com> schrieb am Do., 20.08.2015, 8:38:

**Comment by dimuravyev** [comment]
I cloned whole repo. Script works fine, but not detect telegram (v0.8.52). I tried change icons for telegram manually in 
```
~/.TelegramDesktop/tdata/ticons
```
but it did not help. Moreover, such a directory does not exist since version 0.8.43
```
Chromium -- fixed using google-chrome-no-notification.svg
Chromium -- fixed using google-chrome-no-notification-disabled.svg
Chromium -- fixed using google-chrome-notification.svg
Chromium -- fixed using google-chrome-notification-disabled.svg
Dropbox -- fixed using dropboxstatus-busy.svg
Dropbox -- fixed using dropboxstatus-busy2.svg
Dropbox -- fixed using dropboxstatus-idle.svg
Dropbox -- fixed using dropboxstatus-logo.svg
Dropbox -- fixed using dropboxstatus-x.svg
My Weather Indicator -- fixed using weather-clear-night.svg
My Weather Indicator -- fixed using weather-clear.svg
My Weather Indicator -- fixed using weather-fog.svg
My Weather Indicator -- fixed using weather-clouds-night.svg
My Weather Indicator -- fixed using weather-clouds.svg
My Weather Indicator -- fixed using weather-few-clouds-night.svg
My Weather Indicator -- fixed using weather-few-clouds.svg
My Weather Indicator -- fixed using weather-snow.svg
My Weather Indicator -- fixed using weather-storm.svg
Skype -- fixed using skype-status-invisible-notification.svg
Skype -- fixed using skype-status-connecting-1.svg
Skype -- fixed using skype-status-away-notification.svg
Skype -- fixed using skype-status-connected-notification.svg
Skype -- fixed using skype-status-disturb-notification.svg
Skype -- fixed using skype-status-offline-notification.svg
Skype -- fixed using skype-status-offline.svg
Skype -- fixed using skype-status-connected.svg
Skype -- fixed using skype-status-away.svg
Skype -- fixed using skype-status-connecting-0.svg
Skype -- fixed using skype-status-invisible.svg
Skype -- fixed using skype-status-disturb.svg
Skype -- fixed using skype-status-connecting-2.svg
Skype -- fixed using skype-status-connecting-3.svg
```

**Comment by bil-elmoussaoui** [comment]
How did you installed this version of Telegram?

**Comment by dimuravyev** [comment]
I just copied bin files into /opt
```
dima@dima:~$ l /opt/telegram/
Telegram*  Updater*
```

**Comment by bil-elmoussaoui** [comment]
I updated my telegram version to the latest version too, and i still have this folder :/ 
can you run this in your terminal 
` cd / & sudo find -name icomute_22_0.png`

**Comment by dimuravyev** [comment]
In telegram (v0.8.38) i coped custom icons to
```
~/.TelegramDesktop/tdata/ticons
```
and it worked. 
After update telegram to 0.8.43, it stopped using custom icons. I tried fresh install, I removed telegram settings directory
```
~/.TelegramDesktop
```
but it did not help.
In new version directory
```
~/.TelegramDesktop/tdata/ticons
```
not exists.

**Comment by dimuravyev** [comment]
```
sudo find / -name icomute_22_0.png
```
0 result

**Comment by dimuravyev** [comment]
For pantheon and xfce custom icons works fine

**Comment by bil-elmoussaoui** [comment]
can you check the config folder ? .config in your home directory. The defaults icons are shown ?

**Comment by dimuravyev** [comment]
No telegram icons in .config directory.
Telegram start log
```
$ ./Telegram
libs init..
loading gtk-3 with version 0..
could not load gtk-3 without version.
loading gtk-x11-2.0 with version 0..
could not load gtk-x11-2.0 without version.
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 78: saw unknown, expected number
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 78: saw unknown, expected number
```

**Comment by wa4557** [comment]
Could you try sth like:
`sudo updatedb`
`locate icomute`

**Comment by dimuravyev** [comment]
> Could you try sth like:
sudo updatedb
locate icomute

no results

**Comment by wa4557** [comment]
how strange. And `find . -iname *.png /opt/telegram` ?

**Comment by dimuravyev** [comment]
> how strange. And find . -iname *.png /opt/telegram ?

```
$ ls -a /opt/telegram/
.  ..  Telegram  Updater
```
```
$ find ~/.TelegramDesktop -iname *.png
/home/dima/.TelegramDesktop/tdata/icon.png
```

**Comment by bil-elmoussaoui** [comment]
Share the output of ` cd /home/dima/.TelegramDesktop/tdata/ && ls`

**Comment by bil-elmoussaoui** [comment]
I guess i know what's the issue. Try this? `dpkg -l | grep libappindicator*` if the result is none you will need to isntall `libappindicator` , you can do that with `sudo apt-get install libappindicator3-1 libappindicator1`

**Comment by dimuravyev** [comment]
```
$ cd /home/dima/.TelegramDesktop/tdata/ && ls
D877F783D5D3EF8C  D877F783D5D3EF8C1  icon.png  settings0  version
```
after start telegram
![teelgram]
(https://dl.dropboxusercontent.com/u/14927997/2015-08-20_20%E2%88%B658%E2%88%B608.png)

**Comment by bil-elmoussaoui** [comment]
Telegram is a Qt application and so uses `/tmp` to store the icons. But if you have `libappindicator` installed it will use it instead of Qt indicators.

**Comment by dimuravyev** [comment]
```
$ sudo apt-get install libappindicator3-1 libappindicator1
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libappindicator1 is already the newest version.
libappindicator3-1 is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 11 not upgraded.
```

**Comment by bil-elmoussaoui** [comment]
@dimuravyev try installing the patched version of Sni-Qt like mentioned in the readme. Restart your machine, reopen telegram and share the ouput of `cd /tmp & ls`

**Comment by dimuravyev** [comment]
```
/tmp$ ls
18b1957cde65f95f6bf14f4964d716f0-{87A94AB0-E370-4cde-98D3-ACC110C5967D}  qt-trayicon-nS2330.png
config-err-df1GFB                                                        unity_support_test.0
```

**Comment by bil-elmoussaoui** [comment]
And when you received a notification, did any other file is created in `/tmp`?

**Comment by dimuravyev** [comment]
```
$ ls
18b1957cde65f95f6bf14f4964d716f0-{87A94AB0-E370-4cde-98D3-ACC110C5967D}  qt-trayicon-wZ2330.png
config-err-df1GFB                                                        unity_support_test.0
```
new file `qt-trayicon-wZ2330.png`

**Comment by bil-elmoussaoui** [comment]
:( It's just impossible to fix. As the icons will be removed every time you close telegram. Please report that to [tdesktop](https://github.com/telegramdesktop/tdesktop). The only way to deal with Qt indicators was installing the patched version of sni-qt. But as telegram does not create any `sni-qt_x_y` folder we can't do anything about it. You can have more informations about Qt indicators in the Hardcode-Tray wiki!

**Comment by dimuravyev** [comment]
thanks a lot

**Comment by bil-elmoussaoui** [comment]
@dimuravyev Share the link of the issue there if you want, and you're welcome!
